version: '3.8'

services:
  app:
    image: flask-app:3324
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development      